defaults:
  - _self_
  - data: multidataset
  - model: pi3
  - trainer: default
  - paths: default
  - optional train: null
seed: 42


# configs/trainer/default.yaml 或相应位置
callbacks:
  - _target_: lightning.pytorch.callbacks.ModelCheckpoint
    monitor: "val/total_loss"       # 监控的指标
    mode: "min"               # 指标越小越好
    save_top_k: 3             # 保存最好的3个模型
    save_last: True           # 始终保存最后一个模型 (last.ckpt)
    filename: "pi3-{epoch:02d}-{val_loss:.2f}"
#dataset:
#  _target_: training.dataset.multidataset_module.MultiDatasetModule
#  roots:
#    - dataset/processed_wildrgbd
#    - dataset/processed_midair
#    - dataset/processed_sceneflow
#  split: train
#  num_views: 4
#  batch_size: 4
#  num_workers: 8